# Generated by Django 3.1.3 on 2021-01-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_level',
            field=models.CharField(choices=[('Beginner', 'beginner'), ('Advanced', 'advanced'), ('Intermediate', 'intermediate')], default='beginner', max_length=200),
        ),
    ]
