# Generated by Django 3.1.3 on 2021-02-01 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210201_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_pdf', models.FileField(upload_to='notes/files')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_notes', to='courses.module')),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='text',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='video',
            name='created',
        ),
        migrations.RemoveField(
            model_name='video',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='video',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(default=0, upload_to='course/files'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='module',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='module_videos', to='courses.module'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_level',
            field=models.CharField(choices=[('Beginner', 'beginner'), ('Advanced', 'advanced'), ('Intermediate', 'intermediate')], default='beginner', max_length=200),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
