# Generated by Django 3.1.3 on 2021-02-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210201_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_level',
            field=models.CharField(choices=[('Intermediate', 'intermediate'), ('Advanced', 'advanced'), ('Beginner', 'beginner')], default='beginner', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(default=0, upload_to='course/files'),
        ),
    ]
