# Generated by Django 3.1.3 on 2021-02-01 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20210201_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_level',
            field=models.CharField(choices=[('Intermediate', 'intermediate'), ('Beginner', 'beginner'), ('Advanced', 'advanced')], default='beginner', max_length=200),
        ),
        migrations.AlterField(
            model_name='note',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='courses.module'),
        ),
        migrations.AlterField(
            model_name='video',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.module'),
        ),
    ]
